import os
from dotenv import load_dotenv

load_dotenv(override=True)


LANGSMITH_API_KEY=os.getenv('LANGSMITH_API_KEY')


DASHSCOPE_API_KEY=os.getenv('DASHSCOPE_API_KEY')
DEEPSEEK_API_KEY=os.getenv('DEEPSEEK_API_KEY')
ZHIPU_API_KEY=os.getenv('ZHIPU_API_KEY')
MIMOXIAOMI_API_KEY=os.getenv('MIMOXIAOMI_API_KEY')


DASHSCOPE_API_URL=os.getenv('DASHSCOPE_API_URL')
DEEPSEEK_API_URL=os.getenv('DEEPSEEK_API_URL')
ZHIPU_API_URL=os.getenv('ZHIPU_API_URL')
MIMOXIAOMI_API_URL = os.getenv('MIMOXIAOMI_API_URL')
LOCAL_BASE_URL=os.getenv('LOCAL_BASE_URL')
